include(FetchContent)

FETCHCONTENT_DECLARE(web49 GIT_REPOSITORY https://github.com/FastVM/Web49 GIT_TAG main)
FETCHCONTENT_MAKEAVAILABLE(web49)
INCLUDE_DIRECTORIES(PUBLIC ${web49_SOURCE_DIR}/src)

# FILE(GLOB_RECURSE web49_SOURCE_FILES CONFIGURE_DEPENDS ${web49_SOURCE_DIR}/src/*.c ${web49_SOURCE_DIR}/src/api/*.c)
